name: "GitHub Actions Weather Bot" 

on: 
  schedule: 
  - cron: '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Install node"
        uses: actions/setup-node@v1
        uses: actions/checkout@v1
      - name: "Install NPM dependences"
        run: npm install
      - name: "Run code"
        run: node index.js
        env: 
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          WEATHER_API_TOKEN: ${{secrets.WEATHER_API_TOKEN}}